export const images = {
  blur: 'https://dhix.dhinsights.org/wp-content/uploads/2022/01/blur-dark.png',
  logo_primary:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/DHInsights.svg',
  logo_newsletter:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_newsletter.svg',
  logo_footer:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_footer.svg',
  logo_dha:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_dha.png',
  logo_dhx:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_dhx.svg',
  logo_events:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_events.png',
  logo_dhx_analytics_dark:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/dhx-analytics-dark.svg',
  logo_dhx_analytics_purple:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/dhx-analytics-white.png',
  logo_dhx_analytics_white:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/dhi-analytics-white.svg',
  logo_dhx_analytics_white_vertical:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/dhi-analytics-white-vertical.svg',
  logo_dhx_analytics_light:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/dhx-analytics-light.svg',
  logo_aehia:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_aehia.png',
  logo_aehis:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_aehis.png',
  logo_aehit:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_aehit.png',
  logo_ahima:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_ahima.png',
  logo_chime:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/logo_chime.png',
  mostwiredThumb:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/most-wired-menu.png',
  spacer: 'https://dhix.dhinsights.org/wp-content/uploads/2022/01/spacer.jpg',
  spacer_square:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/spacer_square.jpg',
  spacer_thin:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/spacer_thin.jpg',
  newsletter:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/newsletter.png',
  newsletter_bg:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/new-newsletter-bg-scaled.jpg',
  featured_event:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/featured-event.jpg',
  security:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/security.jpg',
  sidebarPlaceholder:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/sidebarPlaceholder.jpg',
  articleThumbPlaceholder:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/articleThumbPlaceholder.jpg',
  sidebar_bg:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/sidebar_bg.jpg',
  home_hero_bg:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/home-hero-bg.jpg',
  analytics_thumb_1:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/analyticsThumb1.jpg',
  analytics_thumb_2:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/analyticsThumb2.jpg',
  analytics_thumb_3:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/analyticsThumb3.jpg',
  access_portal_hero:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/mostwired-hero-scaled.jpg',
  home_hero_thumb_bg:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/home-hero-bg-1.jpg',
  most_wired_hero:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/most-wired-hero-scaled.jpg',
  most_wired_thumb1:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/most-wired-thumb1.jpg',
  most_wired_thumb2:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/most-wired-thumb2.jpg',
  x_background_thin:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/x-background-thin.jpg',
  most_wired_trend:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/most-wired-trend-uncropped.png',
  expand_your_reach:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/expand-your-reach.png',
  integrated_campaign:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/integrated-campain.png',
  contact_background:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/01/contact-background.png',
  dhax_new:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dhax-new.svg',
  dha_white_new:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dha-white.png',
  dha_logo_bold_dark:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dha-logo-bold-dark.png',
  dha_logo_bold_white:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/DHA-Logo-Bold-Lockup-03.png',
  dha_logo_bold_mix:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/DHA-Logo-Bold-Lockup-01.png',
  dha_logo_regular_dark:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dha-logo-regular-dark.png',
  dha_logo_regular_mix:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dha-logo-regular-mix.png',
  dhi_logo_bold_dark:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dhi-logo-bold-dark.png',
  dhi_logo_bold_white:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dhi-logo-bold-white.png',
  dhi_logo_regular_mix:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dhi-logo-regular-mix.png',
  dhx_logo_bold_dark:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/logo_primary.png',
  dhc_logo_bold_white:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dhc_white.png',
  dhc_logo_regular_mix:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/dhc-logo-regular-mix.png',
  advertise_logo:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/advertise_logo.svg',
  advertise_expand_your_reach:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/advertise-expland-your-reach.png',
  advertise_bg:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/advertise-background-scaled.jpg',
  advertise_integrated_campaign:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/advertise-integrated-campain-scaled.jpg',
  advertise_x_factor:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/advertise-x-factor-revised.png',
  social_share_bg:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/social-share-bg.jpg',
  social_people:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/social-people.png',
  insight_bg:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/insight-bg.jpg',
  insight_bg_thumb:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/02/insight-bg-thumb.jpg',
  sponsored_by_Imprivata:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/03/Imprivata.png',
  sponsored_by_HCI:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/03/HCI-Group.png',
  sponsored_by_FHA:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/03/First-Health-Advisory.png',
  sponsored_by_Clearsense:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/03/Clearsense.png',
  sponsored_by_Cerner:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/03/Cerner.png',
  sponsored_by_CereCore:
    'https://dhix.dhinsights.org/wp-content/uploads/2022/03/CereCore.png',
}
